# develop
server:
  port: 9000
  servlet:
    encoding:
      charset: UTF-8
      enable: true
      force: true
  tomcat:
    threads:
      max: 100
      min-spare: 50
    accept-count: 50 # 작업 큐
# 키 생성 커맨드
# keytool -genkey -storetype PKCS12 -keyalg EC -sigalg SHA256withECDSA -groupname secp256r1 -validity 365 -keystore arotein-keystore.p12 -alias arotein-keystore
#  ssl:
#    key-store: arotein-keystore.p12
#    key-store-type: PKCS12
#    key-store-password: ${SSL_PASSWORD}
#    key-alias: arotein-keystore
#    enabled-protocols: TLSv1.2, TLSv1.3
#  http2.enabled: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/ssgbuild?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${SSG_DB_USERNAME}
    password: ${SSG_DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true
        query.in_clause_parameter_padding: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update
#===================================================

logging.level:
  root: info
#  org.hibernate:
#    SQL: debug

global:
  jwt-token:
    signer: ${SSG_JWT_SIGNER}
