# develop
server:
  port: 9001
  servlet:
    encoding:
      charset: UTF-8
      enable: true
      force: true
  tomcat:
    threads:
      max: 200
      min-spare: 50
    accept-count: 50 # 작업 큐

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.145.206.143:3306/ssgbuild?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${SSG_DB_USERNAME}
    password: ${SSG_DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true
        query.in_clause_parameter_padding: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: validate
#  security:
#    oauth2.client.registration:
#      google:
#        client-id: ${OAUTH2_GOOGLE_ID}
#        client-secret: ${OAUTH2_GOOGLE_SECRET}
#        scope: email, profile

#===================================================
logging:
  level:
    root: info
    org.hibernate:
        SQL: debug

global:
  jwt-token:
    signer: ${SSG_JWT_SIGNER}
